### ISSUE TITLE
Add State, Territory, City data to search parameters 

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#112]
Use google sheets data located in the transhousingrelief@gmail.com google drive for search parameters

**Comment by levis501** [comment]
@turtles , @hexixt Can you suggest a method for converting the city/state data into javascript as in https://github.com/TransgenderHousingRelief/TransgenderHousingRelief/blob/master/client/src/data/locations.js ?   I can write a script to do it without much trouble if needed

**Comment by levis501** [comment]
This PR is ready for review.  The main purposes of these changes are to:

- add script to convert cities spreadsheet to cities.json
- add script to convert housing and legal resource links to legal-housing-resources.json
- import cities data directly from cities.json instead of locations.js
- provide README to describe how to use the tools

https://github.com/TransgenderHousingRelief/TransgenderHousingRelief/pull/126

**Comment by k-stewart** [comment]
Since the PR is merged, is the issue ready to close?
